# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ./ECommerce.Web

pool:
  vmImage: windows-latest

stages:
- stage: Web
  displayName: 'Web Stage'
  jobs:
  - job: Web_Build_Job
    displayName: 'Web Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionspec: '20.14.0'
    - script: |
        npm install --legacy-peer-deps
        npm run build
      workingDirectory: '$(build.sourcesdirectory)/ECommerce.Web/'
      displayName: 'Npm install and build'
    - script: |
        npx playwright install
        npx playwright-test
      workingDirectory: '$(build.sourcesdirectory)/ECommerce.Web/'
      displayName: 'Run Playwright Tests'

